config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :generics

end

app/models/generic.rb
class Generic < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :generics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/generics_controller.rb
class GenericsController < ApplicationController
  before_action :set_generic, only: [:show, :edit, :update, :destroy]

  # GET /generics
  # GET /generics.json
  def index
    @generics = Generic.all
  end

  # GET /generics/1
  # GET /generics/1.json
  def show
  end

  # GET /generics/new
  def new
    @generic = Generic.new
  end

  # GET /generics/1/edit
  def edit
  end

  # POST /generics
  # POST /generics.json
  def create
    @generic = Generic.new(generic_params)

    respond_to do |format|
      if @generic.save
        format.html { redirect_to @generic, notice: 'Generic was successfully created.' }
        format.json { render :show, status: :created, location: @generic }
      else
        format.html { render :new }
        format.json { render json: @generic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /generics/1
  # PATCH/PUT /generics/1.json
  def update
    respond_to do |format|
      if @generic.update(generic_params)
        format.html { redirect_to @generic, notice: 'Generic was successfully updated.' }
        format.json { render :show, status: :ok, location: @generic }
      else
        format.html { render :edit }
        format.json { render json: @generic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generics/1
  # DELETE /generics/1.json
  def destroy
    @generic.destroy
    respond_to do |format|
      format.html { redirect_to generics_url, notice: 'Generic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_generic
      @generic = Generic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def generic_params
      params.require(:generic).permit(:one, :two, :three, :four, :five, :six, :seven, :eight, :nine, :ten, :eleven, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/generics_helper.rb
module GenericsHelper
end

app/views/generics/_form.html.erb
<%= form_for(@generic) do |f| %>
  <% if @generic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@generic.errors.count, "error") %> prohibited this generic from being saved:</h2>

      <ul>
      <% @generic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Title of Degree or Certificate Program
    <% f.label :one %><br>
    <%= f.text_field :one %>
  </div>
  <div class="field">
    Degree Level
    <% f.label :two %><br>
    <%= f.text_field :two %>
  </div>
  <div class="field">
    Name of Academic Department (if relevant):
    <% f.label :three %><br>
    <%= f.text_field :three %>
  </div>
  <div class="field">
    Name of College/School/Branch:
    <% f.label :four %><br>
    <%= f.text_field :four %>
  </div>
  <div class="field">
    Academic Year/Assessment Period:
    <% f.label :five %><br>
    <%= f.text_field :five %>
  </div>
  <div class="field">
    Submitted By (include email address):
    <% f.label :six %><br>
    <%= f.text_field :six %>
  </div>
  <div class="field">
    Date Submitted to College/School/Branch for Review:
    <% f.label :seven %><br>
    <%= f.date_select :seven %>
  </div>
  <div class="field">
    Date Reviewed by College Assessment and Review Committee (CARC) or the equivalent:
    <% f.label :eight %><br>
    <%= f.date_select :eight %>
  </div>
  <div class="field">
    State whether ALL of the program’s student learning outcomes (SLOs) are targeted/assessed/measured within one year, two years, OR three years:
    <% f.label :nine %><br>
    <%= f.text_area :nine %>
  </div>
  <div class="field">
    If the program’s SLO1’s are targeted/assessed/measured within two years or three years, please state whether this assessment record focuses on SLOs from the first year, second year, or third year:
    <% f.label :ten %><br>
    <%= f.text_area :ten %>
  </div>
  <div class="field">
    Describe the actions and/or improvements that were implemented during the previous reporting period (provide relevant evidence):
    <% f.label :eleven %><br>
    <%= f.text_area :eleven %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/generics/edit.html.erb
<h1>Editing Generic</h1>

<%= render 'form' %>

<%= link_to 'Show', @generic %> |
<%= link_to 'Back', generics_path %>

app/views/generics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Generics</h1>

<table>
  <thead>
    <tr>
      <th>Title of Degree or Certificate Program</th>
      <th>Degree Level</th>
      <th>Name of Academic Department (if relevant):</th>
      <th>Name of College/School/Branch:</th>
      <th>Academic Year/Assessment Period:</th>
      <th>Submitted By (include email address):</th>
      <th>Date Submitted to College/School/Branch for Review:</th>
      <th>Date Reviewed by College Assessment and Review Committee (CARC) or the equivalent:</th>
      <th>State whether ALL of the program’s student learning outcomes (SLOs) are targeted/assessed/measured within one year, two years, OR three years:</th>
      <th>If the program’s SLO’s are targeted/assessed/measured within two years or three years, please state whether this assessment record focuses on SLOs from the first year, second year, or third year:</th>
      <th>Describe the actions and/or improvements that were implemented during the previous reporting period (provide relevant evidence):</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @generics.each do |generic| %>
      <tr>
      <% if user_signed_in? %>
      <% if current_user.id == generic.user_id %>
        <td><%= generic.one %></td>
        <td><%= generic.two %></td>
        <td><%= generic.three %></td>
        <td><%= generic.four %></td>
        <td><%= generic.five %></td>
        <td><%= generic.six %></td>
        <td><%= generic.seven %></td>
        <td><%= generic.eight %></td>
        <td><%= generic.nine %></td>
        <td><%= generic.ten %></td>
        <td><%= generic.eleven %></td>
        <td><%= link_to 'Show', generic %></td>
        <td><%= link_to 'Edit', edit_generic_path(generic) %></td>
        <td><%= link_to 'Destroy', generic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Generic', new_generic_path %>

app/views/generics/new.html.erb
<h1>New Generic</h1>

<%= render 'form' %>

<%= link_to 'Back', generics_path %>

app/views/generics/show.html.erb
<p>
  <strong>Title of Degree or Certificate Program:</strong>
  <%= @generic.one %>
</p>

<p>
  <strong>Degree Level:</strong>
  <%= @generic.two %>
</p>

<p>
  <strong>Name of Academic Department (if relevant):</strong>
  <%= @generic.three %>
</p>

<p>
  <strong>Name of College/School/Branch:</strong>
  <%= @generic.four %>
</p>

<p>
  <strong>Academic Year/Assessment Period:</strong>
  <%= @generic.five %>
</p>

<p>
  <strong>Submitted By (include email address):</strong>
  <%= @generic.six %>
</p>

<p>
  <strong>Date Submitted to College/School/Branch for Review:</strong>
  <%= @generic.seven %>
</p>

<p>
  <strong>Date Reviewed by College Assessment and Review Committee (CARC) or the equivalent:</strong>
  <%= @generic.eight %>
</p>

<p>
  <strong>State whether ALL of the program’s student learning outcomes (SLOs) are targeted/assessed/measured within one year, two years, OR three years:</strong>
  <%= @generic.nine %>
</p>

<p>
  <strong>If the program’s SLO’s are targeted/assessed/measured within two years or three years, please state whether this assessment record focuses on SLOs from the first year, second year, or third year:</strong>
  <%= @generic.ten %>
</p>

<p>
  <strong>Describe the actions and/or improvements that were implemented during the previous reporting period (provide relevant evidence):</strong>
  <%= @generic.eleven %>
</p>

<%= link_to 'Edit', edit_generic_path(@generic) %> |
<%= link_to 'Back', generics_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>University</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>


<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>